{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "archflow.fullname" . }}
  labels: {{ include "archflow.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "archflow.fullname" . }}-backend
                port:
                  number: {{ .Values.service.backend.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "archflow.fullname" . }}-frontend
                port:
                  number: {{ .Values.service.frontend.port }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ include "archflow.fullname" . }}-tls
  {{- end }}
{{- end }}
