"""add source_handle target_handle to connections

Revision ID: 32be253b4921
Revises: b0c0fef60ed2
Create Date: 2026-04-16 10:56:23.878150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32be253b4921'
down_revision: Union[str, Sequence[str], None] = 'b0c0fef60ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('source_handle', sa.String(length=50), nullable=True))
    op.add_column('connections', sa.Column('target_handle', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'target_handle')
    op.drop_column('connections', 'source_handle')
    # ### end Alembic commands ###
