"""add activity_log table

Revision ID: 59b3c470f2e1
Revises: 5c4164b64c8a
Create Date: 2026-04-16 13:00:57.854908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59b3c470f2e1'
down_revision: Union[str, Sequence[str], None] = '5c4164b64c8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('target_type', sa.Enum('OBJECT', 'CONNECTION', 'DIAGRAM', name='activity_target_type'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('CREATED', 'UPDATED', 'DELETED', name='activity_action'), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_log_created_at', 'activity_log', ['created_at'], unique=False)
    op.create_index('ix_activity_log_target', 'activity_log', ['target_type', 'target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activity_log_target', table_name='activity_log')
    op.drop_index('ix_activity_log_created_at', table_name='activity_log')
    op.drop_table('activity_log')
    # ### end Alembic commands ###
