"""initial schema

Revision ID: b0c0fef60ed2
Revises: 
Create Date: 2026-04-15 13:42:16.522068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0c0fef60ed2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_objects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('SYSTEM', 'ACTOR', 'EXTERNAL_SYSTEM', 'GROUP', 'APP', 'STORE', 'COMPONENT', name='object_type'), nullable=False),
    sa.Column('scope', sa.Enum('INTERNAL', 'EXTERNAL', name='object_scope'), nullable=False),
    sa.Column('status', sa.Enum('LIVE', 'FUTURE', 'DEPRECATED', 'REMOVED', name='object_status'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('technology', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('owner_team', sa.String(length=255), nullable=True),
    sa.Column('external_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['model_objects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_objects_owner_team', 'model_objects', ['owner_team'], unique=False)
    op.create_index('ix_model_objects_parent_id', 'model_objects', ['parent_id'], unique=False)
    op.create_index('ix_model_objects_status', 'model_objects', ['status'], unique=False)
    op.create_index('ix_model_objects_type', 'model_objects', ['type'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('connections',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('protocol', sa.String(length=100), nullable=True),
    sa.Column('direction', sa.Enum('UNIDIRECTIONAL', 'BIDIRECTIONAL', name='connection_direction'), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['model_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['model_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_connections_source_id', 'connections', ['source_id'], unique=False)
    op.create_index('ix_connections_source_target', 'connections', ['source_id', 'target_id'], unique=False)
    op.create_index('ix_connections_target_id', 'connections', ['target_id'], unique=False)
    op.create_table('diagrams',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('SYSTEM_LANDSCAPE', 'SYSTEM_CONTEXT', 'CONTAINER', 'COMPONENT', 'CUSTOM', name='diagram_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope_object_id', sa.UUID(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scope_object_id'], ['model_objects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagram_objects',
    sa.Column('diagram_id', sa.UUID(), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['diagram_id'], ['diagrams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_id'], ['model_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_diagram_objects_diagram_id', 'diagram_objects', ['diagram_id'], unique=False)
    op.create_index('ix_diagram_objects_object_id', 'diagram_objects', ['object_id'], unique=False)
    op.create_index('uq_diagram_object', 'diagram_objects', ['diagram_id', 'object_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_diagram_object', table_name='diagram_objects')
    op.drop_index('ix_diagram_objects_object_id', table_name='diagram_objects')
    op.drop_index('ix_diagram_objects_diagram_id', table_name='diagram_objects')
    op.drop_table('diagram_objects')
    op.drop_table('diagrams')
    op.drop_index('ix_connections_target_id', table_name='connections')
    op.drop_index('ix_connections_source_target', table_name='connections')
    op.drop_index('ix_connections_source_id', table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_model_objects_type', table_name='model_objects')
    op.drop_index('ix_model_objects_status', table_name='model_objects')
    op.drop_index('ix_model_objects_parent_id', table_name='model_objects')
    op.drop_index('ix_model_objects_owner_team', table_name='model_objects')
    op.drop_table('model_objects')
    # ### end Alembic commands ###
